name: KTB_BE CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

  build-and-push-image:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Portainer Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.PORTAINER_REGISTRY_URL }}
          username: ${{ secrets.PORTAINER_REGISTRY_USER }}
          password: ${{ secrets.PORTAINER_REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build --platform linux/amd64 -t registry.ktbcommunity.cloud/ktb_be:0.0.0 .
          docker push registry.ktbcommunity.cloud/ktb_be:0.0.0

  deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Create .env file
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env
          echo "DB_USER_NAME=${{ secrets.DB_USER_NAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "JWT_KEY=${{ secrets.JWT_KEY }}" >> .env
          echo "AT_MS=${{ secrets.AT_MS }}" >> .env
          echo "RT_MS=${{ secrets.RT_MS }}" >> .env
          echo "AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}" >> .env
          echo "AWS_BUCKET_REGION=${{ secrets.AWS_BUCKET_REGION }}" >> .env
          echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> .env
          echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> .env

      - name: Transfer .env file to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".env"
          target: "/home/${{ secrets.SERVER_USER }}"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Portainer Registry에 로그인
            echo ${{ secrets.PORTAINER_REGISTRY_PASSWORD }} | docker login ${{ secrets.PORTAINER_REGISTRY_URL }} -u ${{ secrets.PORTAINER_REGISTRY_USER }} --password-stdin
            
            # 최신 이미지 pull
            docker pull registry.ktbcommunity.cloud/ktb_be:0.0.0
            
            # 기존 컨테이너 중지 및 삭제
            if [ $(docker ps -q -f name=backend-api) ]; then
              docker stop backend-api
            fi
            if [ $(docker ps -a -q -f name=backend-api) ]; then
              docker rm backend-api
            fi

            # 새 컨테이너 실행 (--env-file 옵션 추가)
            docker run -d -p 8080:8080 --name backend-api --env-file /home/${{ secrets.SERVER_USER }}/.env registry.ktbcommunity.cloud/ktb_be:0.0.0
